using Microsoft.Extensions.AI;
using UglyToad.PdfPig;
using UglyToad.PdfPig.Content;
using UglyToad.PdfPig.DocumentLayoutAnalysis.PageSegmenter;
using UglyToad.PdfPig.DocumentLayoutAnalysis.WordExtractor;

namespace BrixCMS.Open.Services.Ingestion;

public class PDFDirectorySource(
    string sourceDirectory,
    IEmbeddingGenerator<string, Embedding<float>> embeddingGenerator) : IIngestionSource
{
    // Generate a unique ID for the file based on its name
    public static string SourceFileId(string path) => Path.GetFileName(path);

    // Generate a version based on the last write time (UTC)
    public static string SourceFileVersion(string path) => File.GetLastWriteTimeUtc(path).ToString("o");

    public string SourceId => $"{nameof(PDFDirectorySource)}:{sourceDirectory}";

    public Task<IEnumerable<IngestedDocument>> GetNewOrModifiedDocumentsAsync(IReadOnlyList<IngestedDocument> existingDocuments)
    {
        var results = new List<IngestedDocument>();

        if (!Directory.Exists(sourceDirectory))
        {
            return Task.FromResult(Enumerable.Empty<IngestedDocument>());
        }

        var sourceFiles = Directory.GetFiles(sourceDirectory, "*.pdf");

        // Group existing documents by ID to compare versions
        var existingDocumentsById = existingDocuments
            .GroupBy(d => d.DocumentId)
            .ToDictionary(
                g => g.Key,
                g => g.OrderByDescending(d => d.DocumentVersion).First()
            );

        foreach (var sourceFile in sourceFiles)
        {
            var sourceFileId = SourceFileId(sourceFile);
            var sourceFileVersion = SourceFileVersion(sourceFile);

            var existingDocumentVersion = existingDocumentsById.TryGetValue(sourceFileId, out var existingDocument)
                ? existingDocument.DocumentVersion
                : null;

            if (existingDocumentVersion != sourceFileVersion)
            {
                results.Add(new IngestedDocument
                {
                    Key = Guid.CreateVersion7().ToString(),
                    SourceId = SourceId,
                    DocumentId = sourceFileId,
                    DocumentVersion = sourceFileVersion
                });
            }
        }

        return Task.FromResult((IEnumerable<IngestedDocument>)results);
    }

    public Task<IEnumerable<IngestedDocument>> GetDeletedDocumentsAsync(IReadOnlyList<IngestedDocument> existingDocuments)
    {
        var currentFiles = Directory.GetFiles(sourceDirectory, "*.pdf");
        var currentFileIds = currentFiles.Select(SourceFileId).ToHashSet();

        var deletedDocuments = existingDocuments.Where(d => !currentFileIds.Contains(d.DocumentId));
        return Task.FromResult(deletedDocuments);
    }

    public async Task<IEnumerable<IngestedChunk>> CreateChunksForDocumentAsync(IngestedDocument document)
    {
        var filePath = Path.Combine(sourceDirectory, document.DocumentId);

        // Open the PDF document
        using var pdf = PdfDocument.Open(filePath);

        // Extract and chunk text from all pages
        var paragraphs = pdf.GetPages().SelectMany(GetPageParagraphs).ToList();

        var chunks = new List<IngestedChunk>();

        foreach (var p in paragraphs)
        {
            // GENERATE VECTOR: This prevents the SQLite (NULL) error
            // Text is already chunked by GetPageParagraphs (max 200 words/chars per logic)
            var embedding = await embeddingGenerator.GenerateAsync(p.Text);

            chunks.Add(new IngestedChunk
            {
                Key = Guid.CreateVersion7().ToString(),
                DocumentId = document.DocumentId,
                PageNumber = p.PageNumber,
                Text = p.Text,
                Vector = embedding.Vector // Assign the vector generated by the AI Service (e.g., Ollama)
            });
        }

        return chunks;
    }

    private static IEnumerable<(int PageNumber, int IndexOnPage, string Text)> GetPageParagraphs(Page pdfPage)
    {
        var words = NearestNeighbourWordExtractor.Instance.GetWords(pdfPage.Letters);
        var textBlocks = DocstrumBoundingBoxes.Instance.GetBlocks(words);

        var allChunks = new List<(int PageNumber, int IndexOnPage, string Text)>();
        int chunkIndex = 0;

        foreach (var block in textBlocks)
        {
            var cleanedText = block.Text.ReplaceLineEndings(" ").Trim();
            if (string.IsNullOrWhiteSpace(cleanedText)) continue;

            foreach (var subParagraph in SplitIntoChunks(cleanedText, 80))
            {
                allChunks.Add((pdfPage.Number, chunkIndex++, subParagraph));
            }
        }

        return allChunks;
    }

    private static List<string> SplitIntoChunks(string text, int maxWords)
    {
        var words = text.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (words.Length <= maxWords) return [text];

        var chunks = new List<string>();
        var sb = new System.Text.StringBuilder();
        int count = 0;
        foreach (var word in words)
        {
            if (count > 0 && count >= maxWords)
            {
                chunks.Add(sb.ToString().TrimEnd());
                sb.Clear();
                count = 0;
            }
            sb.Append(word).Append(' ');
            count++;
        }
        if (sb.Length > 0) chunks.Add(sb.ToString().TrimEnd());
        return chunks;
    }
}